services:
  # Serviço do frontend (Vite/Quasar)
  frontend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-frontend
    container_name: my-app-frontend
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app
    ports:
      - "3000:3000"  # Porta do Vite (frontend)
    environment:
      - NODE_ENV=local
    networks:
      - my-network
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "npm i && npm run build && npm run dev"]

  # Serviço do backend (Laravel)
  backend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-backend
    container_name: my-app-backend
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/vendor
    ports:
      - "8000:8000"  # Porta do Laravel
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:some_generated_key
    networks:
      - my-network
    depends_on:
      - db
    command: ["php", "artisan", "serve", "--host=localhost", "--port=8000"]

  # Banco de dados PostgreSQL
  db:
    image: postgres:16
    container_name: my-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
