version: '3.8'

services:
  # Serviço do frontend (Vite/Quasar)
  frontend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-frontend
    container_name: my-app-frontend
    working_dir: /usr/src/app
    ports:
      - "3000:3000"  # Porta do Vite (frontend)
    environment:
      - NODE_ENV=${APP_ENV}
    networks:
      - my-network
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "npm i && npm run build && npm run dev"]

  # Serviço do backend (Laravel com Nginx)
  backend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-backend  # Usando o Dockerfile-backend com Nginx
    container_name: my-app-backend
    working_dir: /var/www/html  # Diretório do Laravel no container
    volumes:
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"  # Porta 8000 para o Laravel via Artisan (serve)
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}  # Certifique-se de gerar uma chave no seu ambiente
    networks:
      - my-network
    depends_on:
      - db
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  # Banco de dados PostgreSQL
  db:
    image: postgres:16
    container_name: my-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
