services:
  # Serviço do frontend (Vite/Quasar)
  frontend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-frontend
    container_name: my-app-frontend
    working_dir: /var/www/html
    ports:
      - "3000:3000"  # Porta do Vite (frontend)
    environment:
      - NODE_ENV=${APP_ENV}
    volumes:
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
    networks:
      - my-network
    depends_on:
      - backend
    command: ["/bin/sh", "-c", "npm i && npm run build && npm run dev"]

  # Banco de dados PostgreSQL
  db:
    image: postgres:latest
    container_name: my-db
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_SCHEMA: ${DB_SCHEMA}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-entrypoint-initdb.d/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh 
    ports:
      - "5432:5432"
    networks:
      - my-network
    command:
      ["postgres", "-c", "listen_addresses=0.0.0.0"]

  # Serviço do backend (Laravel com Nginx)
  backend:
    build:
      context: .  # Contexto de construção para a pasta única
      dockerfile: Dockerfile-backend  # Usando o Dockerfile-backend com Nginx
    container_name: my-app-backend
    working_dir: /var/www/html  # Diretório do Laravel no container
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:8000"  # Porta 8000 para o Laravel via Artisan (serve)
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}  # Certifique-se de gerar uma chave no seu ambiente
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - my-network
    depends_on:
      - db
    command: ['sh', '-c', "export DB_HOST=db && php artisan migrate --force && DB_HOST=${DB_HOST} php artisan serve --host=0.0.0.0 --port=8000"]

networks:
  my-network:
    driver: bridge
